### ISSUE TITLE
Build Python wheels for Apple Silicon M1

### ISSUE THREAD

**Issue by Stranger6667** [Stranger6667/css-inline#102]
Links:
- How it is done in Rust-analyzer - https://github.com/lnicola/rust-analyzer/blob/master/.github/workflows/release.yaml#L185
- more notes - https://github.com/shepmaster/rust/blob/silicon/silicon/README.md

```
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-apple-darwin
        profile: minimal
        override: true
```
