### ISSUE TITLE
Double quotes in font-family name break generated style attribute

### ISSUE THREAD

**Issue by Bartvaderkin** [Stranger6667/css-inline#333]
I found this CSS rule with double quotes in the font-family values, and it looks like the inliner doesn't transform the quote style so the copied values break the double quotes of the generated style attribute:

Our case is easily fixable by using single quotes (and of course these particular font names don't even have to be quoted), but it feels like there could be an issue:

````css
h1 {
    color: #000000;
    font-family: "Ubuntu", "Helvetica", Arial, sans-serif;
    font-weight: 600;
    padding: 0;
    margin: 0;
}
````

```html
<h1 style="color: #0084BB;font-family: "Ubuntu", "Helvetica", Arial, sans-serif;font-weight: 600;padding: 0;margin: 0">test</h1>
---------------------------------------^
```

This is on Python 3.11.5 and css-inline 0.13.0
