### ISSUE TITLE
Enable installing css-inline in pyodide

### ISSUE THREAD

**Issue by MarcSkovMadsen** [Stranger6667/css-inline#411]
I would like to use great tables + polars in pyodide. I can see its currently not possible because css-inline is a dependency of great-tables and css-inline cannot be installed.

Please make it possible to install css-inline with pyodide. Thanks so much.

![image](https://github.com/user-attachments/assets/c6b9bca2-f5da-44a6-b417-60f7744ba612)

**Comment by Stranger6667** [comment]
Hi @MarcSkovMadsen 

Sounds good to me! That should not be a problem to add. This package already has a `wasm32` build with JS bindings, and I don't see a blocker on supporting the `wasm32-unknown-emscripten` target in Python bindings (a few minor tweaks will be required around resolving support).

**Comment by Stranger6667** [comment]
So, locally I was able to successfully build a wasm32 wheel with pyodide. I am going to do some maintenance work in the repo and will setup this build in CI + make a release.

**Comment by Stranger6667** [comment]
I updated the Python bindings & added a job that builds a wheel via PyOdide. However, I am not 100% sure what would be the best way to distribute it as PyPI does not support wasm32 wheels. Probably I can just attach this wheel to GitHub releases, but it does not seem super convenient. Additionally, I think it will make sense to make a PR to the PyOdide repo, so the wheel can be built in-tree.

Meanwhile, I'll make a new release with changes that include support for wasm32.

**Comment by MarcSkovMadsen** [comment]
I'm not an expert. I can see that support for pyoide for some packages is requested in like https://github.com/pyodide/pyodide/issues. For example https://github.com/pyodide/pyodide/issues/2933. In this example its currently possible to download wasm32 builds from github. But in https://github.com/apache/arrow/issues/34996#issuecomment-2562936085 its stated to be possible to install with micropip when pyodide 0.27.0 is released. In the issue its also possible to see how difficult it is (for me) to use a github artifact in for example py.cafe.

**Comment by Stranger6667** [comment]
Thank you for the additional details! 

I've published a [GitHub release](https://github.com/Stranger6667/css-inline/releases/tag/python-v0.14.6) with a pyodide-compatible wheel, so a direct link can be used for the in-tree build in the pyodide repo. Over the weekend I'll push a PR that adds `css-inline` there. Something like this:

```
package:
  name: css-inline
  version: 0.14.5
  top-level:
    - css_inline
source:
  url: https://github.com/Stranger6667/css-inline/releases/download/python-v0.14.6/css_inline-0.14.6-cp37-abi3-pyodide_2024_0_wasm32.whl
  sha256: ea273aecd8d232275f713c2778d5a5d9e622a1b7fd2d1124ac97aed22e8c991e
about:
  home: https://github.com/Stranger6667/css-inline
  summary: High-performance library for inlining CSS into HTML 'style' attributes
  license: MIT
extra:
  recipe-maintainers:
    - Stranger6667
```
